apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mmoran-harness/applicationset-example.git
        revision: HEAD
        files:
        - path: "examples/git-generator-files-discovery/cluster-config/**/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: 780e0e79
      source:
        repoURL: https://github.com/mmoran-harness/applicationset-example.git
        targetRevision: HEAD
        path: "examples/git-generator-files-discovery/apps/guestbook"
      destination:
        #server: https://kubernetes.default.svc
        server: '{{cluster.address}}'
        namespace: guestbook
